"""category model add deleted_at column

Revision ID: c7c93015fbd1
Revises: 3489e8fd186b
Create Date: 2025-05-12 06:53:59.758859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c93015fbd1'
down_revision: Union[str, None] = '3489e8fd186b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=450), nullable=False),
    sa.Column('refresh_token', sa.String(length=450), nullable=False),
    sa.Column('ip', sa.String(length=40), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('access_token')
    )
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_verify_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verify_expired_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verify_expired_at')
    op.drop_column('users', 'email_verify_token')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('categories', 'deleted_at')
    op.drop_table('user_tokens')
    # ### end Alembic commands ###
