"""revision

Revision ID: eea91648980c
Revises: c7c93015fbd1
Create Date: 2025-05-12 14:25:49.019472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea91648980c'
down_revision: Union[str, None] = 'c7c93015fbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('choices', 'option_text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.add_column('questions', sa.Column('slug', sa.String(length=200), nullable=False))
    op.add_column('questions', sa.Column('references', sa.Text(), nullable=True))
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.create_unique_constraint(None, 'questions', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.alter_column('questions', 'question',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('questions', 'references')
    op.drop_column('questions', 'slug')
    op.alter_column('choices', 'option_text',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
